language: node_js

node_js:
- "10"

install:
  - npm ci

jobs:
  include:
    - stage: "Lint and Test"
      script: npm run lint
      name: "Linting"
    - script: npm run test:travis
      name: "Test"
